version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install packages
          command: apt-get -y update; apt-get -y install git build-essential
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Configure kernel
          command: make defconfig
      - run:
          name: Build kernel
          command: make -j2
