version: 2
jobs:
  dependencies:
    pre:
      - sudo apt-get -y update
      - sudo apt-get -y install git build-essential
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date

